services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      # Use host.docker.internal to connect to your local PostgreSQL
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5432/musician_management
    networks:
      - app-network
    command: npm run dev

networks:
  app-network:
    driver: bridge